# Generated by Django 6.0.6 on 2026-06-03 21:38

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.PositiveSmallIntegerField(default=3)),
                ('horas_semana', models.PositiveSmallIntegerField(default=4)),
                ('nivel_semestre', models.SmallIntegerField(blank=True, null=True)),
                ('electiva', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cursos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('departamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('edificio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'edificios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estudiantes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'periodos_academicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CursoPrerrequisito',
            fields=[
                ('pk', models.CompositePrimaryKey('curso', 'prerrequisito', blank=True, editable=False, primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='prerrequisitos_rel', to='api.curso')),
                ('prerrequisito', models.ForeignKey(db_column='prerrequisito_id', on_delete=django.db.models.deletion.CASCADE, related_name='requerido_por_rel', to='api.curso')),
            ],
            options={
                'db_table': 'curso_prerrequisitos',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='departamento',
            field=models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api.departamento'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('docente_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo_maximo', models.CharField(blank=True, max_length=100, null=True)),
                ('dedicacion', models.CharField(blank=True, max_length=40, null=True)),
                ('rol', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_vinculacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='api.departamento')),
            ],
            options={
                'db_table': 'docentes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('aula_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='Salon de clase', max_length=60)),
                ('nombre', models.CharField(max_length=30)),
                ('piso', models.SmallIntegerField(blank=True, null=True)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('tiene_proyector', models.BooleanField(default=False)),
                ('tiene_internet', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('edificio', models.ForeignKey(blank=True, db_column='edificio_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='api.edificio')),
            ],
            options={
                'db_table': 'aulas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoCurso',
            fields=[
                ('grupo_id', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(default='Presencial', max_length=30)),
                ('nombre_grupo', models.CharField(max_length=10)),
                ('cupo_maximo', models.PositiveSmallIntegerField(default=30)),
                ('curso', models.ForeignKey(db_column='curso_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='api.curso')),
                ('docente', models.ForeignKey(db_column='docente_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='api.docente')),
                ('periodo', models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='api.periodoacademico')),
            ],
            options={
                'db_table': 'grupos_curso',
                'ordering': ['periodo', 'curso', 'nombre_grupo'],
                'unique_together': {('curso', 'periodo', 'nombre_grupo')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_aplicacion', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='api.grupocurso')),
            ],
            options={
                'db_table': 'evaluaciones',
                'ordering': ['fecha_aplicacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Homologacion',
            fields=[
                ('homologacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('curso_origen', models.CharField(max_length=150)),
                ('institucion_origen', models.CharField(blank=True, max_length=150, null=True)),
                ('nota_origen', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateField(default=datetime.date.today)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('curso_destino', models.ForeignKey(blank=True, db_column='curso_destino_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homologaciones', to='api.curso')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='homologaciones', to='api.estudiante')),
            ],
            options={
                'db_table': 'homologaciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario_id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.ForeignKey(db_column='aula_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.aula')),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.grupocurso')),
            ],
            options={
                'db_table': 'horarios',
                'ordering': ['dia', 'hora_inicio'],
                'unique_together': {('aula', 'dia', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='MaterialCurso',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('publicado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='api.grupocurso')),
            ],
            options={
                'db_table': 'materiales_curso',
                'ordering': ['-publicado_en'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('matricula_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Cancelada', 'Cancelada'), ('Retirada', 'Retirada'), ('Finalizada', 'Finalizada'), ('Pendiente pago', 'Pendiente pago')], default='Activa', max_length=30)),
                ('fecha_matricula', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.estudiante')),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.grupocurso')),
                ('periodo', models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='api.periodoacademico')),
            ],
            options={
                'db_table': 'matriculas',
                'ordering': ['-fecha_matricula'],
                'unique_together': {('estudiante', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionFinal',
            fields=[
                ('cal_final_id', models.AutoField(primary_key=True, serialize=False)),
                ('nota_calculada', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_definitiva', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('aprobado', models.BooleanField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('matricula', models.OneToOneField(db_column='matricula_id', on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_final', to='api.matricula')),
            ],
            options={
                'db_table': 'calificaciones_finales',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(blank=True, max_length=40, null=True)),
                ('referencia', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(default='Confirmado', max_length=30)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.estudiante')),
                ('periodo', models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.periodoacademico')),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(max_length=10)),
                ('numero_doc', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personas',
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('tipo_doc', 'numero_doc')},
            },
        ),
        migrations.CreateModel(
            name='MatriculaHistorial',
            fields=[
                ('historial_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('matricula', models.ForeignKey(db_column='matricula_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='api.matricula')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='registrado_por', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cambios_matricula', to='api.persona')),
            ],
            options={
                'db_table': 'matricula_historial',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='persona',
            field=models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='api.persona'),
        ),
        migrations.AddField(
            model_name='docente',
            name='persona',
            field=models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='api.persona'),
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('programa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nivel_formacion', models.CharField(max_length=60)),
                ('modalidad', models.CharField(default='Presencial', max_length=30)),
                ('creditos_totales', models.SmallIntegerField(blank=True, null=True)),
                ('duracion_semestres', models.SmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='api.departamento')),
                ('director', models.ForeignKey(blank=True, db_column='director_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas_dirigidos', to='api.docente')),
            ],
            options={
                'db_table': 'programas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('evento_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=60, null=True)),
                ('aplica_todos', models.BooleanField(default=True)),
                ('programa', models.ForeignKey(blank=True, db_column='programa_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='api.programa')),
            ],
            options={
                'db_table': 'eventos_calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='api.programa'),
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('sancion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('resuelto', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='api.estudiante')),
            ],
            options={
                'db_table': 'sanciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAcademica',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('atendida_por', models.ForeignKey(blank=True, db_column='atendida_por', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_atendidas', to='api.persona')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='api.estudiante')),
            ],
            options={
                'db_table': 'solicitudes_academicas',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('syllabus_id', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo_general', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('bibliografia', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('grupo', models.OneToOneField(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='api.grupocurso')),
            ],
            options={
                'db_table': 'syllabus',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('tutoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion_min', models.SmallIntegerField(blank=True, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=30, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(blank=True, db_column='curso_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='api.curso')),
                ('docente', models.ForeignKey(db_column='docente_id', on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='api.docente')),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='tutorias', to='api.estudiante')),
            ],
            options={
                'db_table': 'tutorias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password_hash', models.TextField()),
                ('rol', models.CharField(max_length=30)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='api.persona')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('auditoria_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=80)),
                ('operacion', models.CharField(max_length=1)),
                ('registro_id', models.IntegerField()),
                ('datos_antes', models.JSONField(blank=True, null=True)),
                ('datos_despues', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='api.usuario')),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('asistencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('justificada', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='api.estudiante')),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='api.grupocurso')),
                ('horario', models.ForeignKey(db_column='horario_id', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='api.horario')),
            ],
            options={
                'db_table': 'asistencia',
                'ordering': ['-fecha'],
                'unique_together': {('grupo', 'estudiante', 'horario', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='NotaEvaluacion',
            fields=[
                ('nota_id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ausente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='notas_evaluacion', to='api.estudiante')),
                ('evaluacion', models.ForeignKey(db_column='evaluacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api.evaluacion')),
            ],
            options={
                'db_table': 'notas_evaluacion',
                'ordering': ['-registrado_en'],
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='BecaEstudiante',
            fields=[
                ('beca_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_beca', models.CharField(max_length=100)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='api.estudiante')),
                ('periodo', models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='api.periodoacademico')),
            ],
            options={
                'db_table': 'becas_estudiante',
                'ordering': ['estudiante', 'periodo'],
                'unique_together': {('estudiante', 'tipo_beca', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusUnidad',
            fields=[
                ('unidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.SmallIntegerField()),
                ('titulo', models.CharField(max_length=120)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('semanas_duracion', models.SmallIntegerField(blank=True, null=True)),
                ('syllabus', models.ForeignKey(db_column='syllabus_id', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='api.syllabus')),
            ],
            options={
                'db_table': 'syllabus_unidades',
                'ordering': ['syllabus', 'numero'],
                'unique_together': {('syllabus', 'numero')},
            },
        ),
    ]
